---
title: "Probabilities & Convolutions"
subtitle: "A Review on Computer Vision Fundamentals"
date: 2025-11-08 
# date-modified: last-modified
format:
    r-wasm/live-html: 
      grid: 
        margin-width: 350px
execute:
  echo: fenced
reference-location: margin
citation-location: margin
bibliography: main.bib
toc: true
toc-location: left
---

# Introduction

Unfortunately, there's going to be a lot of text this time despite the many interactive codes present. So, this blog will be divided into two parts: first, a general, interactive introduction to the concepts we will be reviewing; second, an optional, more in-depth discussion of said topics.

This document demonstrates the use of a number of advanced page layout features to produce an attractive and usable document inspired by the Tufte handout style and the use of Tufte's styles in RMarkdown documents [@sutton2019bitter]. The Tufte handout style is a style that Edward Tufte uses in his books and handouts. Tufte's style is known for its extensive use of sidenotes, tight integration of graphics with text, and well-set typography. Quarto[^1] supports most of the layout techniques that are used in the Tufte handout style for both HTML and LaTeX/PDF output.

[^1]: To learn more, you can read more about [Quarto](https://www.quarto.org) or visit [Quarto's Github repository](https://www.github.com/quarto-dev/quarto-cli).

```{pyodide}
print("ah")
```


# Overview: MAP & MLE

# Overview: Convolution

# In-depth: MAP & MLE

# In-depth: Convolution
